import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import NavBar from '../components/NavBar'
import AxiosWrapper from './api/AxiosWrapper'
import Items from './item'

export default function Home() {
  const [data, setData] = useState(null)
  const [search, setSearch] = useState('')

  useEffect(() => {
    setTimeout(
      () =>
        AxiosWrapper
          .get('/items', search ? { params: { q: search } } : '')
          .then(({ data }) => {
            setData(data.items)
          })
          .catch((error) => {
            setData([])
          }),
      500
    )
  }, [search])

  return (
    <div>
      <Head>
        <title>Catálogo de Productos</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/makeitreal-image.jpg' />
      </Head>

      <main className={styles.main}>
        <NavBar />
        <div className={styles.search}>
          <input
            value={search}
            placeholder='Buscar...'
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <Items data={data} />
      </main>
    </div>
  )
}
